apiVersion: v1
kind: Service
metadata:
  labels:
    app: awesomeapp
  name: awesomeapp
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: awesomeapp
  type: LoadBalancer
