apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: awesomeapp
  name: awesomeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: awesomeapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: awesomeapp
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
